# recalibration (just run the model old version with new sample)
# train (run a new version with new sample and do not compare with the model old version)
# retrain (run a new version with new sample and compare with the model old version)
train_type: "retrain"

version: "v01.2"
old_version: "v01.1"

# Indicate the column that uniquely identifies each record
id_column: "ID_CLIENTE_ANON"
months:
  - 12
  - 10
  - 8
column_aggregation:
#   - true
  - false
flag_creation:
#   - true
  - false
binning:
#   - true
  - false
outlier_cleaning:
#   - true
  - false
standard_scaler: false
overwrite_saved_features: false
#calibrated classifier. If set to False, the process will take significantly longer to find the hyperparameters.
calibrated_classifier: false
#fixed_features:
 #   - 
n_features:
  - automatic
#   - 10
algorithms:
#   - GaussianNB
   - RandomForestClassifier
#   - ExtraTreesClassifier
#    - GradientBoostingClassifier
#    - LGBMClassifier
#   - LogisticRegression
#    - MLPClassifier
hyperparameters:
  RandomForestClassifier:
    max_features: 
        - "sqrt"
    class_weight:
        - None
        - "balanced"
    max_depth:
        - 5
        - 6
        - 8
        - 15
        - 20
        - 25
        - 40
        
  LogisticRegression:
    solver:
        - "saga"
    max_iter:
        - 500
    C:
        - 0.01
        - 0.1
        - 1
        - 10
    class_weight:
        - None
        - "balanced"
        
  MLPClassifier:
    activation:
        - "logistic"
        - "sigmoid"
        - "tanh"
    max_iter:
        - 500
        - 550
        - 600
        - 650
    hidden_layer_sizes:
        - (5,)
        - (10,)
        - (15,)
        - (25,)
        - (40,)
        - (60,)
        
  ExtraTreesClassifier:
    max_features: 
        - "sqrt"
    class_weight:
        - None
        - "balanced"
        - "balanced_subsample"
    max_depth:
        - 5
        - 8
        - 15
        - 20    
        
  GradientBoostingClassifier:
    max_depth:
        - 3
        - 7
        - 11
        - 15
    learning_rate:
        - 0.01
        - 0.05
        - 0.1
        - 0.3
        
  GaussianNB:
    priors:
        - None
        
  LGBMClassifier:
    n_estimators:
        - 100
        - 200
    max_depth: 
        - -1
    learning_rate:
        - 0.025
        - 0.05
        - 0.1
        - 0.15
    class_weight:
        - None
        - "balanced"
    num_leaves: 
        - 10
        - 15
        - 22
        - 31